//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freeform.Rigging.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RiggerTop {
            get {
                return ((double)(this["RiggerTop"]));
            }
            set {
                this["RiggerTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RiggerLeft {
            get {
                return ((double)(this["RiggerLeft"]));
            }
            set {
                this["RiggerLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double RiggerHeight {
            get {
                return ((double)(this["RiggerHeight"]));
            }
            set {
                this["RiggerHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public double RiggerWidth {
            get {
                return ((double)(this["RiggerWidth"]));
            }
            set {
                this["RiggerWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RiggerMaximized {
            get {
                return ((bool)(this["RiggerMaximized"]));
            }
            set {
                this["RiggerMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HelixTop {
            get {
                return ((double)(this["HelixTop"]));
            }
            set {
                this["HelixTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HelixLeft {
            get {
                return ((double)(this["HelixLeft"]));
            }
            set {
                this["HelixLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double HelixHeight {
            get {
                return ((double)(this["HelixHeight"]));
            }
            set {
                this["HelixHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double HelixWidth {
            get {
                return ((double)(this["HelixWidth"]));
            }
            set {
                this["HelixWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HelixMaximized {
            get {
                return ((bool)(this["HelixMaximized"]));
            }
            set {
                this["HelixMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExporterTop {
            get {
                return ((double)(this["ExporterTop"]));
            }
            set {
                this["ExporterTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExporterLeft {
            get {
                return ((double)(this["ExporterLeft"]));
            }
            set {
                this["ExporterLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double ExporterHeight {
            get {
                return ((double)(this["ExporterHeight"]));
            }
            set {
                this["ExporterHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("660")]
        public double ExporterWidth {
            get {
                return ((double)(this["ExporterWidth"]));
            }
            set {
                this["ExporterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExporterMaximized {
            get {
                return ((bool)(this["ExporterMaximized"]));
            }
            set {
                this["ExporterMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ContentBrowserTop {
            get {
                return ((double)(this["ContentBrowserTop"]));
            }
            set {
                this["ContentBrowserTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ContentBrowserLeft {
            get {
                return ((double)(this["ContentBrowserLeft"]));
            }
            set {
                this["ContentBrowserLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double ContentBrowserHeight {
            get {
                return ((double)(this["ContentBrowserHeight"]));
            }
            set {
                this["ContentBrowserHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1100")]
        public double ContentBrowserWidth {
            get {
                return ((double)(this["ContentBrowserWidth"]));
            }
            set {
                this["ContentBrowserWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserMaximized {
            get {
                return ((bool)(this["ContentBrowserMaximized"]));
            }
            set {
                this["ContentBrowserMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ContentBrowserIconSize {
            get {
                return ((int)(this["ContentBrowserIconSize"]));
            }
            set {
                this["ContentBrowserIconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterMA {
            get {
                return ((bool)(this["ContentBrowserFilterMA"]));
            }
            set {
                this["ContentBrowserFilterMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterMAX {
            get {
                return ((bool)(this["ContentBrowserFilterMAX"]));
            }
            set {
                this["ContentBrowserFilterMAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterFBX {
            get {
                return ((bool)(this["ContentBrowserFilterFBX"]));
            }
            set {
                this["ContentBrowserFilterFBX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ContentBrowserFilterFiles {
            get {
                return ((bool)(this["ContentBrowserFilterFiles"]));
            }
            set {
                this["ContentBrowserFilterFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ContentBrowserFilterFolders {
            get {
                return ((bool)(this["ContentBrowserFilterFolders"]));
            }
            set {
                this["ContentBrowserFilterFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterAllImages {
            get {
                return ((bool)(this["ContentBrowserFilterAllImages"]));
            }
            set {
                this["ContentBrowserFilterAllImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterPSD {
            get {
                return ((bool)(this["ContentBrowserFilterPSD"]));
            }
            set {
                this["ContentBrowserFilterPSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterPNG {
            get {
                return ((bool)(this["ContentBrowserFilterPNG"]));
            }
            set {
                this["ContentBrowserFilterPNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterTGA {
            get {
                return ((bool)(this["ContentBrowserFilterTGA"]));
            }
            set {
                this["ContentBrowserFilterTGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContentBrowserFilterJPG {
            get {
                return ((bool)(this["ContentBrowserFilterJPG"]));
            }
            set {
                this["ContentBrowserFilterJPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ContentBrowserViewState {
            get {
                return ((int)(this["ContentBrowserViewState"]));
            }
            set {
                this["ContentBrowserViewState"] = value;
            }
        }
    }
}
